### ISSUE TITLE
Replace mock response to real response

### ISSUE THREAD

**Issue by hckhanh** [hckhanh/donation-form#12]
# References
- https://firebase.google.com/docs/database/
- https://github.com/firebase/emberfire/blob/master/docs/guide/README.md
# Tasks
- [x] Integrate [Realtime Database](https://firebase.google.com/docs/database/) to web app
- [x] Design **donation** model
- [x] Define **donation** service
- [x] Integrate to `donation-form` component
- [x] Refactor `donation-form` component
