### ISSUE TITLE
 Authenticate with Firebase Anonymously

### ISSUE THREAD

**Issue by hckhanh** [hckhanh/donation-form#13]
# References
- https://firebase.google.com/docs/auth/web/anonymous-auth
- https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md
- https://firebase.google.com/docs/database/security
# Targets
- To identify user when they enter the website and perform submit the donation
- ~~Prevent potential bug from misuse of users. When they try to add too much data, it leads to database is full.~~
# Tasks
- [x] Add Firebase Anonymously for [EmberFire](https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md)
- [x] `donation-form` only visible if use is authenticated
- [x] User cannot submit the form with other `userId`
- [x] Only authenticated user has the access to the donations route
- [x] Add userId field for the form
- [x] Update tests of `donation-form`
