### ISSUE TITLE
Add new feed when a user donates

### ISSUE THREAD

**Issue by hckhanh** [hckhanh/donation-form#18]
The new feed will automatically update whenever new user donate.

Refer to http://semantic-ui.com/views/feed.html
# Tasks
- [x] Add `donation-feed` component
- [x] Add `time-status` helper to show the time
- [x] Refactor `donation-form`
- [x] Refactor `donation-feed` component
- [x] Refactor `index` route
- [x] Show **You** for donation  of the owner
- [x] Write tests for `donation-form` component
- [x] Write tests for `donation-feed` component
- [x] Write tests for `owner-name` helper
- [x] Remove `donations` service
- [x] Change the styles padding of the donation feed

**Comment by hckhanh** [comment]
Like button and donation time are the good ideas

**Comment by hckhanh** [comment]
Maybe we should let user scroll and loading :+1:
